### PR TITLE
reorg rust section

### PR DESCRIPTION
**Pull request by ebuchman**
Wanted to get an index of a bunch of the rust projects in one place. There's some duplication eg. CosmWasm is also in the VMs section and some stuff might be listed on the tendermint awesome but seems worth having an index into all the rust projects in one place for now ...

Sorry I pushed a few of these items to master first before this PR ...

### CODE REVIEW

**Comment by marbar3778** [comment]
I'm not entirely sure we want a rust ecosystem section. This will force us to create js and other lang sections. I would advocate against a language ecosystem section that causes duplication.

**Comment by hxrts** [comment]
I suppose the alternative to a rust section would would be an indication after the item `[rust]`

**Comment by okwme** [comment]
I'd sya we should add it for now since it accounts for projects not currently included. This whole repo is getting converted to a spreadsheet that generates a JSON object. This will be possible to use in a build command to generate a markdown file that can accomodate a rust section with the use of a rust tag even if there are redundant entries (which is not a problem as long as they don't need to get updated separately)

**Review by okwme — APPROVED** [review]

**Comment by marbar3778** [comment]
> I'd sya we should add it for now since it accounts for projects not currently included. 

the projects cosmos based though. This goes back to a conversation we had around including projects that have forked the product or are not using the sdk in any way but are being included here.

**Comment by hxrts** [comment]
> the projects are not cosmos based though

what do we consider "cosmos based"? connected to the SDK somehow? seems too narrow and the items listed here are certainly part of the larger ecosystem.

**Comment by marbar3778** [comment]
> what do we consider "cosmos based"? connected to the SDK somehow? seems too narrow and the items listed here are certainly part of the larger ecosystem.

Built using the cosmos-sdk is what I would categorize as cosmos based. Implementing IBC does not categorize as cosmos based as well, I would say. Crypto.com using tendermint does not mean in the cosmos ecosystem. If we are categorizing Tendermint based chains as cosmos based then this kind of goes against the idea of being able to use the sdk with other consensus.

**Comment by marbar3778** [comment]
Just going to merge this to get the information in. We can discuss anything else in an issue or slack, if need be

**Pull request merged**
