### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by faddat**
Mocked up my idea so it's clear

#78 

This creates 3 categories:

Production, testnet, and development

### CODE REVIEW

**Comment by faddat** [comment]
Will update furter

**Comment by marbar3778** [comment]
you can use the draft feature of github to represent draft mode. What the reasoning for separating this category into three sub groups?

**Comment by faddat** [comment]
Because they're very different things.

Production chains are live, and have economies that can be studied and learned from.  

Testnets are much more mature than chains in development, and are interesting to devs, validators, and investors in a different way from production chains.  

Chains in development may be nothing more than a person, an idea and a GitHub repo (maybe not even the repo)

so you'd want to present production first, then testnet, and then in-development, so that a reader can know which is which at a glance.

**Comment by julienrbrt** [comment]
Hey, thanks for your PR!
We've since moved the ecosystem section to https://cosmos.network/ecosystem/apps.

**Pull request closed without merging**
